name: login_screen_homework
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/




  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
          style: italic

    - family: ARCENA
      fonts:
        - asset: assets/fonts/ARCENA.ttf
          style: italic